# Generated by Django 6.0.5 on 2026-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_globalactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cost_index',
        ),
        migrations.AddField(
            model_name='city',
            name='attractions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='avg_food_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='avg_hotel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='avg_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='tourism_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='city',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
