# Generated by Django 6.0.5 on 2026-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_city_country_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
